openai_api_key = "YourKey"
pinecone_api_key = "YourKey"
pinecone_environment = "YourENV"
pinecone_index = "YourIndex"
pinecone_embedding_model = "YourModel"
xata_api_key = "YourKey"
xata_db_url = "YourURL"
langchain_verbose = true
llm_model = "YourModel"
sensitivity_check = true
anonymous_allowed = true
password = "YourKey"
wix_oauth = false
wix_client_id = "YourID"

base_model = "qwen2.5:1.5b-instruct-fp16"
reasoning_model = "deepseek-r1:1.5b-qwen-distill-fp16"

base_model = "qwen2.5:14b-instruct"
reasoning_model = "deepseek-r1:70b"